version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
      - /src/node_modules
    ports:
      - "3000:3000"
